# Generated by Django 5.2 on 2025-12-09 13:02

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_id', models.CharField(editable=False, max_length=6, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='training', max_length=20)),
                ('logo', models.ImageField(blank=True, default='chatbot_logos/default.png', null=True, upload_to='chatbot_logos/')),
                ('dataset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QSCheckout',
            fields=[
                ('checkout_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qs_checkout',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('registration_status', models.CharField(choices=[('registered', 'Registered'), ('activated', 'Activated')], default='registered', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Metric Vibes tools\\LLM Product\\querysafe launched beta\\documents\\files_uploaded'), upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_querySafe.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('user_id', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='user_querySafe.chatbot')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bot', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user_querySafe.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QSBillingDetails',
            fields=[
                ('billing_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_details', to='user_querySafe.qscheckout')),
            ],
            options={
                'db_table': 'qs_billing_details',
            },
        ),
        migrations.CreateModel(
            name='QSPlan',
            fields=[
                ('plan_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('plan_name', models.CharField(max_length=255)),
                ('is_trial', models.BooleanField(default=False)),
                ('require_act_code', models.BooleanField(default=False)),
                ('no_of_bot', models.PositiveIntegerField(default=0)),
                ('no_of_query', models.PositiveIntegerField(default=0)),
                ('no_of_file', models.PositiveIntegerField(default=0)),
                ('max_file_size', models.PositiveIntegerField(default=0, help_text='Max file size in MB')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('public', 'Public'), ('limited', 'Limited'), ('private', 'Private'), ('personal', 'Personal')], default='public', max_length=20)),
                ('days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_plan', models.ForeignKey(blank=True, help_text='Optional: select a parent plan when this is a trial derived from another plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_plans', to='user_querySafe.qsplan')),
            ],
            options={
                'db_table': 'qs_plans',
            },
        ),
        migrations.CreateModel(
            name='QSOrder',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_error_code', models.CharField(blank=True, help_text='Error code from Razorpay if payment failed', max_length=100, null=True)),
                ('razorpay_error_description', models.TextField(blank=True, help_text='Error description from Razorpay if payment failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user_querySafe.qscheckout')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qs_orders', to='user_querySafe.qsplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qs_orders', to='user_querySafe.user', to_field='user_id')),
            ],
            options={
                'db_table': 'qs_orders',
            },
        ),
        migrations.AddField(
            model_name='qscheckout',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qs_checkouts', to='user_querySafe.qsplan'),
        ),
        migrations.CreateModel(
            name='QSPlanAllot',
            fields=[
                ('plan_allot_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('plan_name', models.CharField(max_length=255)),
                ('no_of_bot', models.PositiveIntegerField(default=0)),
                ('no_of_query', models.PositiveIntegerField(default=0)),
                ('no_of_files', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size limit in MB')),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, help_text='Order that activated this plan (Razorpay order_id)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_allots', to='user_querySafe.qsorder')),
                ('parent_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allots', to='user_querySafe.qsplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qs_plan_allots', to='user_querySafe.user', to_field='user_id')),
            ],
            options={
                'db_table': 'qs_plan_allot',
            },
        ),
        migrations.AddField(
            model_name='qscheckout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qs_checkouts', to='user_querySafe.user', to_field='user_id'),
        ),
        migrations.CreateModel(
            name='HelpSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('resolved', 'Resolved'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='user_querySafe.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatbot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to='user_querySafe.user'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('success', 'Success'), ('info', 'Info'), ('warning', 'Warning')], default='primary', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='info', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='user_querySafe.user')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
