# Generated by Django 5.2 on 2025-12-10 06:16
# NOTE: These fields already exist in 0001_initial for helpsupportrequest.
# This migration is a no-op to avoid "column already exists" on PostgreSQL.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0001_initial'),
    ]

    operations = [
        # Intentionally empty — status and updated_at were already created
        # in 0001_initial for helpsupportrequest. The original AddField
        # operations caused "DuplicateColumn" errors on PostgreSQL.
    ]
