# Generated by Django 5.2 on 2025-12-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpsupportrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='helpsupportrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
