# Generated by Django 5.2 on 2025-12-10 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0003_helpsupportrequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFeedback',
            fields=[
                ('feedback_id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('no_of_star', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='user_querySafe.conversation')),
            ],
            options={
                'db_table': 'chatbot_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
