# Generated by Django 5.2 on 2025-12-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0004_chatbotfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpsupportrequest',
            options={},
        ),
    ]
