# Generated by Django 5.2 on 2026-02-06 06:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0005_alter_helpsupportrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotdocument',
            name='document',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ANKUR BANSAL\\PycharmProjects\\querysafebeta\\documents\\files_uploaded'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
