# Generated by Django 5.2 on 2026-02-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0006_alter_chatbotdocument_document_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='bot_instructions',
            field=models.TextField(blank=True, default='', help_text='Custom instructions for the chatbot (tone, personality, restrictions)'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='sample_questions',
            field=models.TextField(blank=True, default='', help_text='Newline-separated starter questions shown in chat widget'),
        ),
    ]
