# Generated by Django 5.2 on 2026-02-06 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0007_chatbot_bot_instructions_chatbot_sample_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='last_trained_at',
            field=models.DateTimeField(blank=True, help_text='Last successful training timestamp', null=True),
        ),
        migrations.CreateModel(
            name='ChatbotURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('is_sitemap', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('crawled', 'Crawled'), ('error', 'Error')], default='pending', max_length=20)),
                ('page_count', models.PositiveIntegerField(default=0, help_text='Number of pages discovered (for sitemaps)')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='user_querySafe.chatbot')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('chatbot', 'url')},
            },
        ),
    ]
