# Generated by Django 5.2 on 2026-02-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0008_chatbot_last_trained_at_chatboturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='qsplan',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='qsplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in INR', max_digits=12),
        ),
    ]
