# Generated by Django 5.2 on 2026-02-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_querySafe', '0010_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='collect_email',
            field=models.BooleanField(default=False, help_text='Require visitor email before chatting'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='collect_email_message',
            field=models.TextField(blank=True, default='Please enter your email to get started.', help_text='Message shown when asking for email'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='visitor_email',
            field=models.EmailField(blank=True, help_text='Email collected from visitor via lead capture', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='helpsupportrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='VisionAPIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_count', models.PositiveIntegerField(default=1)),
                ('call_type', models.CharField(choices=[('training', 'Training Pipeline'), ('chat', 'Chat Response')], default='training', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_usage', to='user_querySafe.chatbot')),
            ],
            options={
                'db_table': 'vision_api_usage',
            },
        ),
    ]
